### ISSUE TITLE
How should back navigation work?

### ISSUE THREAD

**Issue by foozmeat** [foozmeat/hotline#3]
There isn't a standard control in kivy for "back" and I'm hesitant to rely strictly on a gesture for it. I could dedicate a row in the UI for navigation controls and status indicators I guess.

What do you think would work?

**Comment by ashur** [comment]
I agree that gesture-only navigation isn’t the way to go, and that top navigation + status bar would feel familiar to most people.

I’ll start putting together some sketches

**Comment by foozmeat** [comment]
looks like there's an "ActionBar" UI dingus we can maybe use here

https://kivy.org/docs/api-kivy.uix.actionbar.html
